services:
  solar_db:
    image: postgres:latest
    container_name: solar_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: solar_watch
    volumes:
      - postgres_data:/var/lib/postgresql/data

  solar_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solar_backend
    restart: always
    depends_on:
      - solar_db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}

  solar_frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: solar_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - solar_backend

volumes:
  postgres_data:
    driver: local