services:
  postgres:
    image: postgres:17
    container_name: solar_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: solar_watch
    ports:
      - "5432:5432"

  solar-watch-app:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET}
      OPENWEATHER_API_KEY: ${API_KEY}
    ports:
      - "8080:8080"